services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - OMP_NUM_THREADS=2
      - MKL_NUM_THREADS=2
      - TOKENIZERS_PARALLELISM=false
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
